name: Build
on: [push, pull_request]
jobs:
  build:
    name: "Windows Latest VS"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test1
      id: test1
      shell: bash
      run: |
        pwd
        ls -la
      
